version: '3.8'

services:
  # 1. Our NoSQL Database
  mongodb:
    image: mongo:latest
    container_name: etl-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  # 2. Our Cache + Pub/Sub Broker
  redis:
    image: redis:latest
    container_name: etl-redis
    ports:
      - "6379:6379"

  # 3. Our SQL Database (for PostgresLoader strategy)
  postgres:
    image: postgres:16-alpine
    container_name: etl-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: etl_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

# Declare persistent volumes
volumes:
  mongo-data:
  postgres-data: